/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pathways;
import java.awt.*;
/**
 *
 * @author xavierloera
 */
public class Schedule extends javax.swing.JFrame {

        int termpage = 0;
        int info=1;
    /**
     * Creates new form Schedule
     */
    public Schedule() {
        initComponents();
        labelFullName.setText(Test.stu.getFullName());
        labelStudentID.setText(Test.stu.getStudentID());
        labelEmail.setText(Test.stu.getEmail());
        //String termnames[] ={"Term 1"," Term 2", "Term 3", "Term 4","Term 6"};
        //int termpage = 0;
        printtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonLeft = new javax.swing.JButton();
        buttonRight = new javax.swing.JButton();
        labelFullName = new javax.swing.JLabel();
        buttonHome = new javax.swing.JButton();
        labelStudentID = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelColumn1 = new javax.swing.JLabel();
        labelColumn2 = new javax.swing.JLabel();
        labelColumn3 = new javax.swing.JLabel();
        t1c1 = new javax.swing.JLabel();
        t1c2 = new javax.swing.JLabel();
        t1c3 = new javax.swing.JLabel();
        t1c4 = new javax.swing.JLabel();
        t1c5 = new javax.swing.JLabel();
        t1c6 = new javax.swing.JLabel();
        t3c1 = new javax.swing.JLabel();
        t3c2 = new javax.swing.JLabel();
        t3c3 = new javax.swing.JLabel();
        t3c4 = new javax.swing.JLabel();
        t3c5 = new javax.swing.JLabel();
        t3c6 = new javax.swing.JLabel();
        t2c3 = new javax.swing.JLabel();
        t2c5 = new javax.swing.JLabel();
        t2c2 = new javax.swing.JLabel();
        t2c1 = new javax.swing.JLabel();
        t2c4 = new javax.swing.JLabel();
        t2c6 = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textCourse = new javax.swing.JTextField();
        textTerm = new javax.swing.JTextField();
        textRow = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textTerm1 = new javax.swing.JTextField();
        textRow1 = new javax.swing.JTextField();
        buttonMinus = new javax.swing.JButton();
        buttoninfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelINFO = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/left.png"))); // NOI18N
        buttonLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLeftActionPerformed(evt);
            }
        });

        buttonRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/right.png"))); // NOI18N
        buttonRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRightActionPerformed(evt);
            }
        });

        labelFullName.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelFullName.setText("FULLNAME");

        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });

        labelStudentID.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelStudentID.setText("STUDENTID");

        labelEmail.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelEmail.setText("EMAIL");

        labelColumn1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelColumn1.setText("term1");

        labelColumn2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelColumn2.setText("term 2");

        labelColumn3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelColumn3.setText("term3");

        t1c1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t1c1.setText("jLabel1");

        t1c2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t1c2.setText("jLabel1");

        t1c3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t1c3.setText("jLabel1");

        t1c4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t1c4.setText("jLabel1");

        t1c5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t1c5.setText("jLabel1");

        t1c6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t1c6.setText("jLabel1");

        t3c1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t3c1.setText("jLabel1");

        t3c2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t3c2.setText("jLabel1");

        t3c3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t3c3.setText("jLabel1");

        t3c4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t3c4.setText("jLabel1");

        t3c5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t3c5.setText("jLabel1");

        t3c6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t3c6.setText("jLabel1");

        t2c3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t2c3.setText("jLabel1");

        t2c5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t2c5.setText("jLabel1");

        t2c2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t2c2.setText("jLabel1");

        t2c1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t2c1.setText("jLabel1");

        t2c4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t2c4.setText("jLabel1");

        t2c6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        t2c6.setText("jLabel1");

        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PLUS.png"))); // NOI18N
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        jLabel1.setText("COURSE");

        jLabel2.setText("Term");

        jLabel3.setText("Row");

        textCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCourseActionPerformed(evt);
            }
        });

        textTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTermActionPerformed(evt);
            }
        });

        textRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRowActionPerformed(evt);
            }
        });

        jLabel5.setText("Term");

        jLabel6.setText("Row");

        textRow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRow1ActionPerformed(evt);
            }
        });

        buttonMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MINUS.png"))); // NOI18N
        buttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusActionPerformed(evt);
            }
        });

        buttoninfo.setText("Info");
        buttoninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoninfoActionPerformed(evt);
            }
        });

        labelINFO.setColumns(20);
        labelINFO.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelINFO.setRows(5);
        jScrollPane1.setViewportView(labelINFO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonLeft)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(1, 1, 1)
                                .addComponent(textCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textRow, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(buttonAdd)))))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelColumn1)
                    .addComponent(t1c4)
                    .addComponent(t1c5)
                    .addComponent(t1c6)
                    .addComponent(t1c1)
                    .addComponent(t1c2)
                    .addComponent(t1c3))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t2c3)
                        .addComponent(t2c5)
                        .addComponent(t2c2)
                        .addComponent(t2c1)
                        .addComponent(t2c4)
                        .addComponent(t2c6))
                    .addComponent(labelColumn2))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelColumn3)
                        .addGap(7, 7, 7))
                    .addComponent(t3c1)
                    .addComponent(t3c4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t3c2)
                        .addComponent(t3c3)
                        .addComponent(t3c5)
                        .addComponent(t3c6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 811, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(buttonRight))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textTerm1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textRow1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(buttonMinus)))
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttoninfo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFullName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelStudentID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEmail, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonHome)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelFullName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelStudentID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEmail)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonLeft)
                            .addComponent(buttonRight))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(textCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonAdd))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textTerm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textRow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelColumn1)
                                    .addComponent(labelColumn3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t1c1)
                                        .addGap(13, 13, 13)
                                        .addComponent(t1c2)
                                        .addGap(13, 13, 13)
                                        .addComponent(t1c3)
                                        .addGap(13, 13, 13)
                                        .addComponent(t1c4)
                                        .addGap(13, 13, 13)
                                        .addComponent(t1c5)
                                        .addGap(13, 13, 13)
                                        .addComponent(t1c6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t3c1)
                                        .addGap(13, 13, 13)
                                        .addComponent(t3c2)
                                        .addGap(13, 13, 13)
                                        .addComponent(t3c3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(t3c4)
                                        .addGap(14, 14, 14)
                                        .addComponent(t3c5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(t3c6))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelColumn2)
                                .addGap(13, 13, 13)
                                .addComponent(t2c1)
                                .addGap(13, 13, 13)
                                .addComponent(t2c2)
                                .addGap(13, 13, 13)
                                .addComponent(t2c3)
                                .addGap(13, 13, 13)
                                .addComponent(t2c4)
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonMinus)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t2c5)
                                        .addGap(13, 13, 13)
                                        .addComponent(t2c6)))))))
                .addGap(14, 14, 14)
                .addComponent(buttoninfo)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLeftActionPerformed
        if(termpage>0)
        this.termpage-=1;
        printtable();
        repaint();// TODO add your handling code here:
    }//GEN-LAST:event_buttonLeftActionPerformed

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        Welcome start = new Welcome();
        start.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void buttonRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRightActionPerformed
        if(termpage<=7)
        this.termpage+=1;
        printtable();
        repaint();    // TODO add your handling code here:
    }//GEN-LAST:event_buttonRightActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed

            String course = textCourse.getText();
    int term = Integer.parseInt(textTerm.getText())-1;
    int row = Integer.parseInt(textRow.getText())-1;
    Course replacement=Data.blank;
        for (Course masterlist : Data.masterlist) {
            if (course.equals(masterlist.getCourseCode()))
              replacement=masterlist;}
    Test.stu.getTerm(term).replaceCourse(replacement,row);
    printtable();
// TODO add your handling code here:
    }//GEN-LAST:event_buttonAddActionPerformed

    private void textCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCourseActionPerformed

    private void textTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTermActionPerformed

    private void textRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRowActionPerformed

    private void textRow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRow1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRow1ActionPerformed

    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinusActionPerformed
            int term = Integer.parseInt(textTerm1.getText())-1;
            int row = Integer.parseInt(textRow1.getText())-1;
            Course replacement=Data.blank;
            Test.stu.getTerm(term).replaceCourse(replacement,row);
            printtable();
// TODO add your handling code here:
    }//GEN-LAST:event_buttonMinusActionPerformed

    private void buttoninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoninfoActionPerformed
    info++; 
    printtable();// TODO add your handling code here:
    }//GEN-LAST:event_buttoninfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Schedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonLeft;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonRight;
    private javax.swing.JButton buttoninfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelColumn1;
    private javax.swing.JLabel labelColumn2;
    private javax.swing.JLabel labelColumn3;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFullName;
    private javax.swing.JTextArea labelINFO;
    private javax.swing.JLabel labelStudentID;
    private javax.swing.JLabel t1c1;
    private javax.swing.JLabel t1c2;
    private javax.swing.JLabel t1c3;
    private javax.swing.JLabel t1c4;
    private javax.swing.JLabel t1c5;
    private javax.swing.JLabel t1c6;
    private javax.swing.JLabel t2c1;
    private javax.swing.JLabel t2c2;
    private javax.swing.JLabel t2c3;
    private javax.swing.JLabel t2c4;
    private javax.swing.JLabel t2c5;
    private javax.swing.JLabel t2c6;
    private javax.swing.JLabel t3c1;
    private javax.swing.JLabel t3c2;
    private javax.swing.JLabel t3c3;
    private javax.swing.JLabel t3c4;
    private javax.swing.JLabel t3c5;
    private javax.swing.JLabel t3c6;
    private javax.swing.JTextField textCourse;
    private javax.swing.JTextField textRow;
    private javax.swing.JTextField textRow1;
    private javax.swing.JTextField textTerm;
    private javax.swing.JTextField textTerm1;
    // End of variables declaration//GEN-END:variables
    public void printtable(){
                String termnames[] ={"Term 1"+String.format(" %.1f",Test.stu.getTerm(0).getTotalUnits()),
            "Term 2"+String.format(" %.1f",Test.stu.getTerm(1).getTotalUnits()), 
            "Term 3"+String.format(" %.1f",Test.stu.getTerm(2).getTotalUnits()), 
            "Term 4"+String.format(" %.1f",Test.stu.getTerm(3).getTotalUnits()),
            "Term 5"+String.format(" %.1f",Test.stu.getTerm(4).getTotalUnits()),
            "Term 6"+String.format(" %.1f",Test.stu.getTerm(5).getTotalUnits()),
            "Term 7"+String.format(" %.1f",Test.stu.getTerm(6).getTotalUnits()),
            "Term 8"+String.format(" %.1f",Test.stu.getTerm(7).getTotalUnits())    };
        labelColumn1.setText(termnames[termpage]);
        labelColumn2.setText(termnames[termpage+1]);
        labelColumn3.setText(termnames[termpage+2]);
        t1c1.setText(Test.stu.getTerm(termpage).getCourse(0).toString());
        t1c2.setText(Test.stu.getTerm(termpage).getCourse(1).toString());
        t1c3.setText(Test.stu.getTerm(termpage).getCourse(2).toString());
        t1c4.setText(Test.stu.getTerm(termpage).getCourse(3).toString());
        t1c5.setText(Test.stu.getTerm(termpage).getCourse(4).toString());
        t1c6.setText(Test.stu.getTerm(termpage).getCourse(5).toString());
        t2c1.setText(Test.stu.getTerm(termpage+1).getCourse(0).toString());
        t2c2.setText(Test.stu.getTerm(termpage+1).getCourse(1).toString());
        t2c3.setText(Test.stu.getTerm(termpage+1).getCourse(2).toString());
        t2c4.setText(Test.stu.getTerm(termpage+1).getCourse(3).toString());
        t2c5.setText(Test.stu.getTerm(termpage+1).getCourse(4).toString());
        t2c6.setText(Test.stu.getTerm(termpage+1).getCourse(5).toString());        
        t3c1.setText(Test.stu.getTerm(termpage+2).getCourse(0).toString());
        t3c2.setText(Test.stu.getTerm(termpage+2).getCourse(1).toString());
        t3c3.setText(Test.stu.getTerm(termpage+2).getCourse(2).toString());
        t3c4.setText(Test.stu.getTerm(termpage+2).getCourse(3).toString());
        t3c5.setText(Test.stu.getTerm(termpage+2).getCourse(4).toString());
        t3c6.setText(Test.stu.getTerm(termpage+2).getCourse(5).toString());
        String bigtext="";
        switch (info%6) {
            case 0:  bigtext = "AREA A – LANGUAGE AND RATIONALITY – 6 semester/9 quarter units minimum \n" +
"1. English Composition course:\n" +
"ENG 001A English Composition I\n" +
"2. One additional course:\n" +
"COM 001, 001H Public Speaking\n" +
"COM 004 Small Group Communications \n" +
"COM 020, 020H Argumentation and Debate \n" +
"ENG 001B English Composition\n" +
"ENG 001C Clear Thinking in Writing\n" +
"EGR 030, Intro to Computing for Engineers \n" +
"FRN 003, 4 Intermediate Language (5ea)\n" +
"MAT 000C, 000CG, 000CM, 009 or a more advanced Math course (3-5 units) \n" +
"PHI 002 Logic\n" +
"PHI 003 Introduction to Ethics\n" +
"POL 020 Controversial Legal Issues\n" +
"REA 054 Critical College Reading & Thinking\n" +
"SOC 016 Introduction to Statistics in Social and Behavioral Sciences \n" +
"SPA 003, 004 Intermediate Language (5ea)";
                     break;
            case 1: bigtext="AREA B – NATURAL SCIENCES – 3semester/4 quarter units minimum\n" +
"These courses examine the physical universe, its life forms and its natural phenomena. Courses with a lab are underlined.\n" +
"ANT 001 Physical Anthropology\n" +
"AST 001 Astronomy\n" +
"AST 003 Astronomy with Lab (4)\n" +
"AST 003H Astronomy with Lab – Honors (4) \n" +
"AST 004 Astrobiology\n" +
"BIO 001A, 001AH, 001B General Biology (5 ea) \n" +
"BIO 004 Microbiology (5)\n" +
"BIO 010 Introduction to Biology\n" +
"BIO 010L Introduction to Biology Lab (1)\n" +
"BIO 011 Human Biology (4)\n" +
"BIO 012 Emerging Infectious Disease\n" +
"BIO 014 Introductory Neuroscience\n" +
"BIO 015 Human Genetics\n" +
"BIO 016 Marine Biology (4)\n" +
"BIO 017, 017H Genetics and Society\n" +
"BIO 019 Oceans: Life in the Sea\n" +
"BIO 022 Anat.& Physiology for Allied Health Workers \n" +
"(4) BIO 025 Environmental Biology\n" +
"BIO 030 Tropical Ecology (3)\n" +
"BIO 030L Tropical Ecology Field Studies (1)\n" +
"BIO 032 California Plants and Animal (4)\n" +
"BIO 047, 048, 048H Human Anatomy, Physiology (5ea)\n" +
"CHM 001A,001AH, 001B, 001BH General Chemistry (5ea)\n" +
"CHM 002 Introductory Chemistry\n" +
"CHM 002L Introduction to Chemistry Lab (1)\n" +
"CHM 012A, 012AH, 012B, 012BH Organic Chemistry (5ea)\n" +
"CHM 030A,030B Fundamentals of Chemistry (4)\n" +
"CHM 060 Survey of General, Organic and Biological Chemistry \n" +
"(4) GEO 001 Introduction to Physical Geography\n" +
"NTR 015 Human Nutrition\n" +
"NTR 040 Nutrition and Disease\n" +
"NTR 052 Nutrition for Children\n" +
"PHY 002A,002B General Physics (5ea)\n" +
"PHY 004A,004B,004C Engineering Physics (5ea)\n" +
"PHY 004D Engineering Physics - Atomic (2)\n" +
"PHY 010 Introduction to Physics (4)\n" +
"PSY 007 Biological Psycholog";
                    break;
            case 2: bigtext="AREA C – HUMANITIES – 3semester/4 quarter units minimum\n" +
"These courses develop an awareness of the ways in which people throughout the ages and in different cultures have responded to themselves and the world around them in artistic and cultural creation. NOTE: Three 1-unit classes alone may not be used to satisfy this category.\n" +
"\n" +
"ARB 001, 002 First, Second Semester Arabic\n" +
"ARB 50A, 50B Beginning Conversational Arabic and Culture \n" +
"ART 001A Survey of Western Art I\n" +
"ART 001B Survey of Western Art II\n" +
"ART 001D Survey of Modern Art\n" +
"ART 004 Art Appreciation\n" +
"ART 007 Survey of Asian Art\n" +
"ART 011 The History of Modern Design (Also GDES 011) ART 031A,B Drawing\n" +
"ART 033A Basic Design: Two-Dimensional\n" +
"ART 033B Basic Design: Three-Dimensional\n" +
"ART 034A,B Introduction to/Advanced Digital Art\n" +
"ART 035A,B Life Drawing\n" +
"ART 039A Survey of Printmaking\n" +
"ART 047A,B Watercolor\n" +
"ART 048A,B Airbrush Painting\n" +
"ART 049A,B Painting\n" +
"ART 065A,B Ceramics-Handbuilding\n" +
"ART 067A,B Ceramics-Potter’s Wheel\n" +
"ART 075A,B Metalsmithing\n" +
"ART 078A,B Furniture Design and Construction\n" +
"ART 085A,B Sculpture\n" +
"ART 088A,B Metal Sculpture Casting\n" +
"CHI 001, 2 First/Second Semester Chinese\n" +
"CHI 050A,B Basic Conversational Chinese\n" +
"COM 012 Intercultural Communication\n" +
"ENG 001B English Composition\n" +
"ENG 005A,B English Literature\n" +
"ENGL 006B World Literature\n" +
"ENG 007A,B American Literature\n" +
"ENG 013 Chicana/o-Latina/o Literature\n" +
"ENG 015 Intro. to Film Analysis (Also HUM 015)\n" +
"ENG 043 Classical Mythology\n" +
"ENG 048 Introduction to Shakespeare\n" +
"ENG 070 Creative Writing\n" +
"FRN 001,2 First/Second Semester French - Elementary (5ea) \n" +
"FRN 003,4 Third/Forth Semester French - Intermediate (5ea) \n" +
"FRN 001L, 2L French Lab (0.5 ea)\n" +
"GDS 011 The History of Modern Design (Also ART 011)\n" +
"GDS 012 History of Photography\n" +
"GDS 015 Photo-media and Social Change\n" +
"GDS 073 Digital Photography\n" +
"HIS 004A, 004AH History of Western Civilization\n" +
"HIS 004B, 004BH History of Western Civilization\n" +
"HIS 015, 015H World History to 1500\n" +
"HIS 016, 016H World History since 1500\n" +
"HIS 017A, 017AH History of the United States to 1877 \n" +
"HIS 017B, 017BH History of the United States since 1877 \n" +
"HIS 033, 033H Women’s Issues Past and Present\n" +
"HUM 001A,001B Human Values in and from the Arts \n" +
"HUM 007 International Films (Also POL 007)\n" +
"(HUM 007 may only be counted in Area C)\n" +
"HUM 015 Intro to Film Analysis (Also ENGL 015)\n" +
"HUM 016A Hispanic Roots and Culture\n" +
"HUM 018, 018H African American Culture/Humanities\n" +
"HUM 020 Asian Roots and Culture\n" +
"HUM 022 Introduction to Islam\n" +
"HUM 024 The Asian American Experience\n" +
"HUM 030, Cultural Studies\n" +
"JPN 001,002 First/Second Semester Japanese - Elementary (5 ea)\n" +
"KIN 041 – 048 All Dance Classes see catalog for complete course titles and units)\n" +
"KIN 080 Dance Appreciation (formerly WHP 040)\n" +
"MUS 005 Fundamentals of Music Theory\n" +
"MUS 006 Commercial Music Theory I\n" +
"MUS 007 Commercial Music Theory II\n" +
"MUS 010 Music Appreciation\n" +
"MUS 016 History of Rock Music\n" +
"MUS 017 Musics of the World\n" +
"MUS 030A,B/031A,B Beginning/Intermediate Piano (1 ea)\n" +
"MUS 032A,B/033A,B Beginning/Intermediate Voice (1 ea)\n" +
"MUS 036A,B Beginning Guitar (1 ea)\n" +
"MUS 041A, B Mission Chorus (1 ea)\n" +
"MUS 048A, B Symphony Orchestra (1 ea)\n" +
"PHI 001 Introduction to Philosophy\n" +
"PHI 002 Logic\n" +
"PHI 003 Introduction to Problems in Ethics\n" +
"PHI 005 Introduction to Social and Political Philosophy (Also POL 003) \n" +
"POL 003 Introduction to Social and Political Philosophy (Also PHI 005) \n" +
"SPA 001,2 First/Second Semester Spanish - Elementary (5ea)\n" +
"SPA 001L,2L Spanish Lab (.5ea)\n" +
"SPA 003,4 Third/Forth Semester Spanish - Intermediate (5ea)\n" +
"SPA 050A,B Basic Conversational Spanish\n" +
"VIE 001,2 First/Second Semester Vietnamese - Elementary (5ea)\n" +
"VIE 049A,B Vietnamese Language & Culture for Fluent Speakers";
                    break;
            case 3: bigtext="AREA D — SOCIAL & BEHAVIORAL SCIENCES\n" +
"Series 1: \n" +
"Social and Behavioral Sciences (3 sem/ 4.5 qtr units): These courses deal with human, social, psychological, political, and economic institutions and behavior and their historical background, selected from among the following:\n" +
"                                                             \n" +
"ANT 003 Cultural Anthropology\n" +
"ANT 045 Human Sexuality (Also PSY/SOC 045)\n" +
"ANT 055 Magic, Witchcraft, & Religion\n" +
"BUS 061 Business and Society\n" +
"CHD 001 Child Growth & Development\n" +
"CHD 002 Child, Family and Community\n" +
"CHD 013 Working with Children in a Diverse Society\n" +
"COM 025 Mass Communication and Society\n" +
"COU 055 Valuing Diversity\n" +
"ECN 001A Principles of Macroeconomics\n" +
"ECN 001B Principles of Microeconomics\n" +
"ECN 006 The Global Economy\n" +
"GEO 002 Introduction to Cultural Geography\n" +
"GEO 006 World Regional Geography\n" +
"GLB 001 Global Perspectives\n" +
"GLB 002 Global Issues\n" +
"GLB 004 The Developing World\n" +
"HIS 004A, 004AH, 004B, 004BH History of Western Civilization \n" +
"HIS 015, 015H World History to 1500\n" +
"HIS 016, 016H World History since 1500\n" +
"HIS 017A, 017AH United States History to 1877\n" +
"HIS 017B, 017BH United States History since 1877\n" +
"HIS 020 History and Geography of California\n" +
"HIS 033, 033H Women’s Issues Past and Present\n" +
"HUM 016A Hispanic Roots and Culture\n" +
"HUM 018, 018H African American Roots and Culture\n" +
"HUM 024 The Asian American Experience\n" +
"POL 001, 001H American Government\n" +
"POL 002 Comparative Government\n" +
"POL 004 International Relations\n" +
"POL 005 Political Science Research Methodology \n" +
"POL 006 Politics of Race, Class and Gender\n" +
"POL 007 International Films) (Also HUMAN 007) (POL 007 may only be counted in Area D)\n" +
"POL 020 Controversial Legal Issues\n" +
"PSY 001, 001H General Psychology\n" +
"PSY 002A Experimental Psychophysiology (4)\n" +
"PSY 007 Biological Psychology\n" +
"PSY 010 Social Psychology\n" +
"PSY 012 Human Growth and Development\n" +
"PYS 015, 015H Introduction to Research Methods\n" +
"PSY 025 Introduction to Abnormal Psychology\n" +
"PSY 030 Psychology of Addiction and Substance Abuse PSY 045 Human Sexuality (Also ANT/SOC 045)\n" +
"SOC 001, 001H Introduction to Sociology\n" +
"SOC 002, 002H Social Problems\n" +
"SOC 021 Sociology of Minorities in the U.S.\n" +
"SOC 040 Marriage and Family\n" +
"SOC 045 Human Sexuality (Also ANT/PSY 045)\n" +
"SOC 047 Sociology of Criminology\n" +
"SOC 050 Introduction to Criminal Justice\n" +
"SOC 054 Concepts of Criminal Law\n" +
"SOC 058 Introduction to Corrections\n" +
"SOC 060 Community and Justice System\n" +
"\n" +
"Series 2: American History and Institutions (3 sem/4 qtr units): \n" +
"Demonstrate proficiency in American history or American government on a departmental examination \n" +
"OR complete a course with a grade of C (or “P”) or better from one of the following:\n" +
"HIS 017A, 017AH History of United States to 1877 \n" +
"HIS 017B, 017BH History of United States since 1877 \n" +
"HIS 020 History and Geography of California \n" +
"POL 001, 001H American Government";
                    break;
            case 4: bigtext="AREA E – LIFELONG LEARNING \n" +
"The Lifelong Learning requirement will be completed by the selection of either:\n" +
"Option 1:                                                                                                                  \n" +
"Three (3) units from Area A-2, B, C or D; OR\n" +
"Option 2:\n" +
"Three (3) units from courses listed below which cultivate self-understanding and development of the student as an integrated individual capable of coping with life in our modern society, assist students to acquire the skills necessary to adapt to change, gain self-understanding, and set achievable goals, and which include consideration of such matters as cognitive, affective and psycho-motor development, health, stress management, and key relationships of humans to their social and physical environment.                      \n" +
"NOTE: \n" +
"All Kinesiology (KIN/WHP/PE) courses are accepted in Area E (except Theory courses). However, only one unit from this area will count for General Education.\n" +
"\n" +
"ANT 045 Human Sexuality (Also PSY/SOC 045) \n" +
"BIO 025 Environmental Biology\n" +
"BUS 061 Business and Society\n" +
"CHD 002 Child, Family and Community\n" +
"CHD 013 Working with Children in a Diverse Society \n" +
"CHD 017 Child Health and Safety\n" +
"CHL 010 Community Health Problems\n" +
"COM 004 Small Group Communication\n" +
"COM 008 Interpersonal Communication\n" +
"COM 012 Introduction to Intercultural Communication \n" +
"COU 005 Strategies for Success\n" +
"COU 012 Careers and Life Styles\n" +
"COU 012A Careers and Life Styles (1)\n" +
"COU 017 Transfer Success and Life Transitions\n" +
"COU 023 Becoming a Master Student-Athlete (2)\n" +
"COU 055 Valuing Diversity\n" +
"GLB 001 Global Perspectives\n" +
"GLB 002 Global Issues\n" +
"HED 002 Health and Lifestyle\n" +
"KIN 078 Introduction to Kinesiology\n" +
"LIB 010 Information Competency (1)\n" +
"LIB 010H Information Competency (1)\n" +
"NTR 015 Human Nutrition\n" +
"NTR 040 Nutrition and Disease\n" +
"NTR 052 Nutrition for Children\n" +
"PSY 012 Human Growth and Development\n" +
"PSY 025 Introduction to Abnormal Psychology\n" +
"PSY 030 Psychology of Addiction and Substance Abuse PSY 045 Human Sexuality (Also ANT/SOC 045)\n" +
"SOC 002, 002H Social Problems\n" +
"SOC 021 Sociology of Minorities in the U.S.\n" +
"SOC 040 Marriage and Family\n" +
"SOC 045 Human Sexuality";
                    break;       
            case 5: bigtext="All Classes\n"+
                    "blank, cis007, cis008, cis037a, cis040, cis043, cis044, cis045, \n"
                    + "math903, math00c, math002, math003a, math003b, egr010, egr023, \n"
                    + "egr024, egr030, eng905ac, eng908, eng001a, eng001b, hed002, phy002a, \n"
                    + "phy004a, phy004b, his004a, his004b, his015, his015h, his017a, his017b, \n"
                    + "his020, his031, rea054, rea961, art001a, art001b, art001d, art031a, art031b, \n"
                    + "art033a, art033b, art034a, art034b, art035a, art035B, art035c,art035d,art049a, \n"
                    + "art049b, art049c, art049d, art065a, art065b, art065c, art065d , art067a, art067b, \n"
                    + "art067c, art067d, art075a, com001, com001h,com004,com008, com012, com020, com020h, \n"
                    + "com025, ecn001a, ecn001b, ecn006, phi001, phi002, phi003, phi005";
                    break;
        }
labelINFO.setText(bigtext);   
        
    }



}
